<a href="https://colab.research.google.com/github/Vishwas2505/Data-Science/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy

In [ ]:
import numpy as np
arr=np.array([1,2,3])
print(arr)

[1 2 3]


In [ ]:
arr_2d=np.array([[1,2,3],[4,5,6]])
print(arr_2d)
print(arr_2d.ndim)

[[1 2 3]
 [4 5 6]]
2


In [ ]:
arr_3d=np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])
print(arr_3d)
print(arr_3d.shape)
print(arr_3d.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
3


In [ ]:
zeros=np.zeros((2,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
ones=np.ones((2,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#random function
r=np.random.random((2,2))
print(r)

[[0.76808228 0.7946149 ]
 [0.36990143 0.58809511]]


In [ ]:
#identity function
i=np.eye(3)
print(i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#with a range of vaules
a=np.arange(0,10,2)
print(a)

[0 2 4 6 8]


In [ ]:
#array attributes
arr1=np.array([[1,2,3],[4,5,6]])
print("Shape:",arr1.shape)
print("size:",arr1.size)
print("data type:",arr1.dtype)
print("dimensions:",arr1.ndim)

Shape: (2, 3)
size: 6
data type: int64
dimensions: 2


In [ ]:
temp_data=np.array([[22,25,20],[24,26,23]])
print(temp_data)

print("Shape:",temp_data.shape)
print("size:",temp_data.size)
print("data type:",temp_data.dtype)
print("dimensions:",temp_data.ndim)


updated_array=np.append(temp_data,[[21,23,22]],axis=0)


sensor_error_flags=np.zeros((2,3))
greenhouse_identity=np.eye(3)

print(updated_array)
print(sensor_error_flags)
print(greenhouse_identity)

[[22 25 20]
 [24 26 23]]
Shape: (2, 3)
size: 6
data type: int64
dimensions: 2
[[22 25 20]
 [24 26 23]
 [21 23 22]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#indexing
arr=np.array([[10,20,30],[40,50,60]])
print(arr[0,2])
print(arr[1,-2])

30
50


In [ ]:
#slicling
print(arr[:,1:])

[[20 30]
 [50 60]]


In [ ]:
shipments=np.array([[50,60,55,70,65,80,90],[40,45,50,60,55,70,75]])
print(shipments[0,2])
print(shipments[1,6])
print("mon-fri",shipments[0:5,0:5])
print("only on weekends:",shipments[:,5:7])
print("apples shifted from wed-sat",shipments[0:1,2:6])
shipments[0,5]=100
print(shipments[0,5])


55
75
mon-fri [[50 60 55 70 65]
 [40 45 50 60 55]]
only on weekends: [[80 90]
 [70 75]]
apples shifted from wed-sat [[55 70 65 80]]
100


In [ ]:
#array operations
a=np.array([1,2,3])
b=np.array([4,5,6])
print("Addition:",a+b)
print("Sub:",a-b)
print("mul:",a*b)
print(a*2)

Addition: [5 7 9]
Sub: [-3 -3 -3]
mul: [ 4 10 18]
[2 4 6]


In [ ]:
#matrix operations
mat1=np.array([[1,2],[3,4]])
mat2=np.array([[2,3],[5,6]])


print("Matrix multiplication",np.dot(mat1,mat2))

Matrix multiplication [[12 15]
 [26 33]]


In [ ]:
#Boardcasting
import numpy as np
a=np.array([1,2,3])
b=2
print(a+b)

[3 4 5]


In [ ]:
#universal functions
x=np.array([1,2,3])
y=np.array([3,4,5])

#arithematicoperations
print("Arithematical operations")
print(np.add(x, y))
print(np.subtract(x, y))
print(np.multiply(x, y))
print(np.divide(x, y))
print(np.power(x, y))
print(np.mod(x, y))

print("\nExponential operations")
#exponential
print(np.exp(x))
print(np.log(x))
print(np.log10(x))
print(np.log2(x))
print(np.expm1(x))

print("\ntrigonmetrical operations")
#trigonmetric
print(np.sin(x))
print(np.cos(x))
print(np.tan(x))
print(np.arcsin(x))
print(np.arccos(x))
print(np.arctan(x))
print(np.degrees(x))
print(np.radians(x))

#rounding
print("\nrounding operations")
print(np.round(x))
print(np.floor(x))
print(np.ceil(x))
print(np.trunc(x))

#statistical
print("\nstatistical operations")
print(np.min(x))
print(np.max(x))
print(np.mean(x))
print(np.std(x))
print(np.var(x))
print(np.sum(x))
print(np.prod(x))

#logical
print("\nlogical operations")
print(np.logical_and(x, y))
print(np.logical_or(x, y))
print(np.logical_not(x))
print(np.logical_xor(x, y))

#comparison
print("\ncomparsion operations")
print(np.greater(x, y))
print(np.less(x, y))
print(np.equal(x, y))
print(np.not_equal(x, y))
print(np.greater_equal(x, y))
print(np.less_equal(x, y))

#bitwise
print("\nbitwise operations")
print(np.bitwise_and(x, y))
print(np.bitwise_or(x, y))
print(np.bitwise_xor(x, y))
print(np.invert(x))

Arithematical operations
[4 6 8]
[-2 -2 -2]
[ 3  8 15]
[0.33333333 0.5        0.6       ]
[  1  16 243]
[1 2 3]

Exponential operations
[ 2.71828183  7.3890561  20.08553692]
[0.         0.69314718 1.09861229]
[0.         0.30103    0.47712125]
[0.        1.        1.5849625]
[ 1.71828183  6.3890561  19.08553692]

trigonmetrical operations
[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
[ 1.55740772 -2.18503986 -0.14254654]
[1.57079633        nan        nan]
[ 0. nan nan]
[0.78539816 1.10714872 1.24904577]
[ 57.29577951 114.59155903 171.88733854]
[0.01745329 0.03490659 0.05235988]

rounding operations
[1 2 3]
[1. 2. 3.]
[1. 2. 3.]
[1. 2. 3.]

statistical operations
1
3
2.0
0.816496580927726
0.6666666666666666
6
6

logical operations
[ True  True  True]
[ True  True  True]
[False False False]
[False False False]

comparsion operations
[False False False]
[ True  True  True]
[False False False]
[ True  True  True]
[False False False]
[ True  True  True]

bitwise o

/tmp/ipython-input-3721625991.py:27: RuntimeWarning: invalid value encountered in arcsin
  print(np.arcsin(x))
/tmp/ipython-input-3721625991.py:28: RuntimeWarning: invalid value encountered in arccos
  print(np.arccos(x))


In [ ]:
farmA=np.array([[10,12,11],[9,11,10],[12,13,14],[8,7,9]])
farmB=np.array([[20,19,21],[18,20,19],[22,23,21],[17,18,16]])
farmC=np.array([[15,16,14],[14,13,15],[16,17,18,],[12,11,13]])
production_all=np.array([farmA,farmB,farmC])
print("shape",production_all.shape)
print("size:",production_all.size)
print("datatype",production_all.dtype)
print("dimensions",production_all.ndim)


#arithematic and aggregatic functions
total_per_farm = production_all.sum(axis=(1, 2))
print("total per farm",total_per_farm)
print("mean for farms",production_all.mean(axis=(1,2)))
print("std of farms",production_all.std(axis=(1,2)))
print("var of farms",production_all.var(axis=(1,2)))

#per hour mult idea
hour_weights=[0.5,1.0,0.75]
weighted_per_panel=np.dot(production_all,hour_weights)
print(weighted_per_panel)

#boardcasting
print("add after production b",production_all[1]+0.5)

#arithematic opeartions
mean_per_farm = production_all.mean(axis=(1, 2))
std_per_farm = production_all.std(axis=(1, 2), ddof=0)
mean_farm_sh = mean_per_farm.reshape(3,1,1)
std_farm_sh = std_per_farm.reshape(3,1,1)

normalized = (production_all - mean_farm_sh) / std_farm_sh
print("normalized shape:", normalized.shape)
print("normalized dtype:", normalized.dtype)
print("normalized first farm (farmA) first row:", normalized[0,0])
print()

#many ufuncs
eps = 1e-9
abs_norm = np.abs(normalized)

exp_norm = np.exp(normalized)
expm1_norm = np.expm1(normalized)
safe_log = np.log(abs_norm + eps)    # log(|x| + eps)
safe_log10 = np.log10(abs_norm + eps)
safe_log2 = np.log2(abs_norm + eps)

# Trigonometric:
sin_norm = np.sin(normalized)
cos_norm = np.cos(normalized)
tan_norm = np.tan(normalized)
# arcsin/arccos require inputs in [-1,1], clip to safe range
clipped_for_arcs = np.clip(normalized, -1.0, 1.0)
arcsin_norm = np.arcsin(clipped_for_arcs)
arccos_norm = np.arccos(clipped_for_arcs)
arctan_norm = np.arctan(normalized)

# degrees/radians example: convert arctan results to degrees
arctan_degrees = np.degrees(arctan_norm)
arctan_radians = np.radians(arctan_degrees)  # should match arctan_norm (roundtrip-ish)

# Rounding:
round_norm = np.round(normalized, 3)
floor_norm = np.floor(normalized)
ceil_norm = np.ceil(normalized)
trunc_norm = np.trunc(normalized)

print("Some ufunc summaries:")
print("exp mean:", np.mean(exp_norm))
print("log (safe) mean:", np.mean(safe_log))
print("sin mean:", np.mean(sin_norm))
print("round (first farm first row):", round_norm[0,0])
print()

#boardcast based on table
high_output = production_all > 20
even_hours_mask = np.array([True, False, True]).reshape(1,1,3)

# Combine masks:
high_and_even = np.logical_and(high_output, even_hours_mask)
high_or_even = np.logical_or(high_output, even_hours_mask)
high_not = np.logical_not(high_output)

print("high_output.any():", high_output.any())
print("high_and_even.any():", high_and_even.any())
print()

# Also use comparison ufuncs:
ge_6 = np.greater_equal(production_all, 6.0)
lt_5 = np.less(production_all, 5.0)
print("Number of readings >=6.0 kWh:", np.sum(ge_6))
print()


shape (3, 4, 3)
size: 36
datatype int64
dimensions 3
total per farm [126 234 174]
mean for farms [10.5 19.5 14.5]
std of farms [1.97905701 1.97905701 1.97905701]
var of farms [3.91666667 3.91666667 3.91666667]
[[25.25 23.   29.5  17.75]
 [44.75 43.25 49.75 38.5 ]
 [34.   31.25 38.5  26.75]]
add after production b [[20.5 19.5 21.5]
 [18.5 20.5 19.5]
 [22.5 23.5 21.5]
 [17.5 18.5 16.5]]
normalized shape: (3, 4, 3)
normalized dtype: float64
normalized first farm (farmA) first row: [-0.25264558  0.75793673  0.25264558]

Some ufunc summaries:
exp mean: 1.598804393115028
log (safe) mean: -0.4170055480646958
sin mean: 6.1679056923619804e-18
round (first farm first row): [-0.253  0.758  0.253]

high_output.any(): True
high_and_even.any(): True

Number of readings >=6.0 kWh: 36



In [ ]:
#reshaping array
a=np.array([1,2,3,4,5,6,6,7])
print(a.reshape(2,4))

[[1 2 3 4]
 [5 6 6 7]]


In [ ]:
#stacking
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [ ]:
#splitting
a=np.array([1,2,3,4,5,6])
print(np.array_split(a,3))

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
#advanced indexing
a=np.array([1,2,3,4,5,6])
print(a[a>4])
#fancy indexing
indices=np.array([0,2,4])
print(a[indices])

[5 6]
[1 3 5]


In [ ]:
#view
arr=np.array([1,2,3,4,5])
x=arr.view()
arr[0]=10
print(arr)
print(x)
#copy
copy=arr.copy()#copy doesnot shared  memory
arr[0]=1
print(arr)
print(copy)

[10  2  3  4  5]
[10  2  3  4  5]
[1 2 3 4 5]
[10  2  3  4  5]


In [ ]:
#saving and loading
a=np.array([1,2,3])
np.save('array.npy',a)
load=np.load('array.npy')
print(load)

[1 2 3]


In [ ]:
#task
a1=np.arange(10,51)
print(a1)
a2=np.random.rand(3,3)
print(a2)

#array attiributes
print("array attirubets")
print(a1.ndim)
print(a1.shape)
print(a1.size)
print(a1.dtype)

#basic
print("---basic operation---")
print(a1+5)
print(a2*2)

#indexing and slicing
print("--indexing and slicing--")
a3=np.arange(1,26)
a3=a3.reshape(5,5)
print(a3)
print(a3.ndim)
print("first row",a3[0,:])
print("last row",a3[4,:])
print("first 3 rows 2 col",a3[0:3,0:2])

#aggergation
print("--aggergation--")
a4 = np.random.randint(10, 101, size=10)
print(a4)
print("max:",a4.max())
print("min:",a4.min())
print("mean:",a4.mean())
print("sum:",a4.sum())

#reshaping
print("--reshaping--")
a5=np.arange(1,13).reshape(3,4)
print(a5)

#boardcasting
print("--boardingcasting--")
a6=np.ones((3,3),dtype=int)
print(a6)
d1=[1,2,3]
print("after adding")
print(a6+d1)

#filtering
print("--filtering--")
a7=np.random.randint(1,51,size=20)
print(a7)
print(a7[a7%5==0])

#matrix multipilaction
print("--matrix multipilaction--")
a8=np.array([[1,2],[3,4]])
a9=np.array([[5,6],[7,8]])
print(np.dot(a8,a9))

#advanced indexing
print("--fancy indexing--")
a10=np.arange(1,17).reshape(4,4)
print(a10)
r=[0,1,2,3]
c=[0,1,2,3]
print(a10[:,])
print("diagonal elements:",a10[[r],[c]])

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
[[0.93066531 0.80978386 0.64394533]
 [0.41499684 0.80164022 0.07594663]
 [0.87005753 0.84903864 0.48771302]]
array attirubets
1
(41,)
41
int64
---basic operation---
[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]
[[1.86133062 1.61956773 1.28789067]
 [0.82999368 1.60328044 0.15189325]
 [1.74011506 1.69807728 0.97542603]]
--indexing and slicing--
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
2
first row [1 2 3 4 5]
last row [21 22 23 24 25]
first 3 rows 2 col [[ 1  2]
 [ 6  7]
 [11 12]]
--aggergation--
[64 59 75 25 15 55 77 74 45 66]
max: 77
min: 15
mean: 55.5
sum: 555
--reshaping--
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
--boardingcasting--
[[1 1 1]
 [1 1 1]
 [1 1 1]]
after adding
[[2 3 4]
 [2 3 4]
 [2 3 4]]
--filtering--
[27 23 27 12 4

IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed